# Numpy -  multidimensional data arrays

## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` you need to import the module, using for example:

In [4]:
import numpy as np

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [5]:
a=np.empty((5,5), dtype=np.float32)
print(a)

[[0.0000000e+00 0.0000000e+00 2.8628528e-42 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.4713634e-43]
 [8.5498489e+20 8.1724465e+20 2.1457666e-07 4.1721428e-08 2.6727581e+23]
 [2.6512448e-09 8.5380742e-07 1.3411041e-08 4.1957918e-08 1.0488336e-08]
 [1.7089910e-04 4.1025846e-08 4.1914014e+21 4.3441902e-05 4.3677341e-05]]


## Creating `numpy` arrays

From the [Numpy documentation](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html) we have that an _array_ is 

_An instance of class ndarray consists of a contiguous one-dimensional segment of computer memory (owned by the array, or by some other object), combined with an indexing scheme that maps N integers into the location of an item in the block._

Said differently, an array is mostly a contiguous block of memory whose parts can be accessed using an indexing scheme.

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [6]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [7]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1.0, 2.], [3.2, 4.5]], dtype=np.float32)

M

array([[1. , 2. ],
       [3.2, 4.5]], dtype=float32)

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [8]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [9]:
v.shape

(4,)

In [10]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [11]:
M.size

4

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [12]:
np.shape(M)

(2, 2)

In [13]:
np.size(M)

4

In [14]:
M.nbytes

16

In [15]:
M.itemsize

4

**Remark.** If you are using IPython then you can see the content of the workspace using the `who` and `whos` commands. IPython is an interactive command-line terminal for Python. It was created by Fernando Perez in 2001. IPython offers an enhanced read-eval-print loop (REPL) environment particularly well adapted to scientific computing. In Jupyter you have Ipython!

In [16]:
who

M	 a	 np	 pydev_jupyter_vars	 remove_imported_pydev_package	 sys	 v	 


In [17]:
whos

Variable                        Type        Data/Info
-----------------------------------------------------
M                               ndarray     2x2: 4 elems, type `float32`, 16 bytes
a                               ndarray     5x5: 25 elems, type `float32`, 100 bytes
np                              module      <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pydev_jupyter_vars              module      <module 'pydev_jupyter_va<...>g/pydev_jupyter_vars.py'>
remove_imported_pydev_package   function    <function remove_imported<...>ackage at 0x7f984a8b4a60>
sys                             module      <module 'sys' (built-in)>
v                               ndarray     4: 4 elems, type `int64`, 32 bytes


So far the `numpy.ndarray` looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [18]:
M.dtype

dtype('float32')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [19]:
M[0,0] = 1

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [20]:
M = np.array([[1, 2], [3, 4]], dtype=np.int16)

M
M.dtype

dtype('int16')

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float128`, `complex128`.

### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

In [21]:
# create a range

x = np.arange(0, 10, 1) # arguments: start, stop, step

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x = np.arange(-1, 1, 0.1)
print(x)
help(np.arange)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]
Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    s

#### linspace and logspace

In [23]:
# using linspace, both end points ARE included
print(np.linspace(0, 10, 10))
help(np.linspace)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to Fa

In [24]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [25]:
print(np.logspace(0, 10, 11, base=np.e))
help(np.logspace)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
  

#### mgrid

In [26]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB

In [27]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [28]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### random data

In [29]:
from numpy import random

In [30]:
# uniform random numbers in [0,1]
random.rand(5,5)

array([[0.22592811, 0.52754462, 0.02798725, 0.86736834, 0.69658629],
       [0.57779161, 0.66896484, 0.79999004, 0.61570481, 0.24041495],
       [0.0910251 , 0.6858372 , 0.22504165, 0.24443407, 0.57397558],
       [0.69792126, 0.08771421, 0.52429766, 0.6136921 , 0.17668769],
       [0.26091999, 0.15398503, 0.08322583, 0.62443303, 0.49070893]])

In [31]:
# standard normal distributed random numbers
random.randn(5,5)

array([[-0.01134721,  0.22297194,  1.18566117,  0.89025787,  0.87300079],
       [-1.43482064, -0.19771416,  0.78006328,  0.88287287,  1.82649669],
       [-0.42387597,  1.53458374,  1.74987352, -1.26646675, -1.92329734],
       [-1.3429954 ,  0.44300943,  1.64161288,  0.23081354,  1.21907963],
       [ 0.50761486, -0.46857891, -1.53402765, -0.42340603, -0.99079776]])

In [32]:
dir(random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponen

#### diag

In [33]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [34]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=-1) 

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

#### zeros and ones

In [35]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## File I/O

### Comma-separated values (CSV)

A very common file format for data files is comma-separated values (CSV), or related formats such as TSV (tab-separated values). To read data from such files into Numpy arrays we can use the `numpy.genfromtxt` function.  

Using `numpy.savetxt` we can store a Numpy array to a file in CSV format:

In [38]:
M = random.rand(5,5)

In [39]:
np.savetxt("random-matrix.csv", M)
#help(np.savetxt)

In [40]:
!cat random-matrix.csv

5.443279477742390959e-02 5.865209021316738491e-01 4.196006560153400233e-01 5.598728231309216818e-01 8.261165895630474543e-01
7.019780916701936491e-01 6.147295804984784784e-01 3.737901725712348133e-01 2.334729330504494715e-01 9.648616521333717166e-01
8.498735996364411571e-01 1.911311449248739303e-01 4.765190484423745820e-01 4.441705714485311152e-01 4.381810086782823577e-01
2.700996665943287134e-01 9.907383530010853701e-01 1.973000634316961488e-01 2.645845054475925995e-01 9.950687784254425017e-01
6.780229006009249604e-01 4.163261586111335344e-01 3.087083416630825861e-01 4.865619905129737743e-01 1.592492525742109644e-01


In [41]:
!pwd

/Users/jodyrobertobattistini/PycharmProjects/pythonProject/NAFML/Notebook


In [42]:
A = np.genfromtxt('random-matrix.csv')
type(A)
#help(np.genfromtxt)


numpy.ndarray

In [43]:
A

array([[0.05443279, 0.5865209 , 0.41960066, 0.55987282, 0.82611659],
       [0.70197809, 0.61472958, 0.37379017, 0.23347293, 0.96486165],
       [0.8498736 , 0.19113114, 0.47651905, 0.44417057, 0.43818101],
       [0.27009967, 0.99073835, 0.19730006, 0.26458451, 0.99506878],
       [0.6780229 , 0.41632616, 0.30870834, 0.48656199, 0.15924925]])

### Numpy's native file format

Useful when storing and reading back numpy array data. Use the functions `numpy.save` and `numpy.load`:

In [44]:
np.save("random-matrix.npy", M)

!file random-matrix.npy

random-matrix.npy: NumPy data file, version 1.0, description {'descr': '<f8', 'fortran_order': False, 'shape': (5, 5), }                                                          


In [45]:
B=np.load("random-matrix.npy")
B

array([[0.05443279, 0.5865209 , 0.41960066, 0.55987282, 0.82611659],
       [0.70197809, 0.61472958, 0.37379017, 0.23347293, 0.96486165],
       [0.8498736 , 0.19113114, 0.47651905, 0.44417057, 0.43818101],
       [0.27009967, 0.99073835, 0.19730006, 0.26458451, 0.99506878],
       [0.6780229 , 0.41632616, 0.30870834, 0.48656199, 0.15924925]])

## More properties of the numpy arrays

In [46]:
M.itemsize # bytes per element

8

In [47]:
M.nbytes # number of bytes

200

In [48]:
M.ndim # number of dimensions

2

In [49]:
whos

Variable                        Type        Data/Info
-----------------------------------------------------
A                               ndarray     5x5: 25 elems, type `float64`, 200 bytes
B                               ndarray     5x5: 25 elems, type `float64`, 200 bytes
M                               ndarray     5x5: 25 elems, type `float64`, 200 bytes
a                               ndarray     5x5: 25 elems, type `float32`, 100 bytes
np                              module      <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pydev_jupyter_vars              module      <module 'pydev_jupyter_va<...>g/pydev_jupyter_vars.py'>
random                          module      <module 'numpy.random' fr<...>umpy/random/__init__.py'>
remove_imported_pydev_package   function    <function remove_imported<...>ackage at 0x7f984a8b4a60>
sys                             module      <module 'sys' (built-in)>
v                               ndarray     4: 4 elems, type `int64`, 32 bytes
x  

## Manipulating arrays

### Indexing

We can index elements in an array using square brackets and indices:

In [50]:
# v is a vector, and has only one dimension, taking one index
v[0]

1

In [51]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M

array([[0.05443279, 0.5865209 , 0.41960066, 0.55987282, 0.82611659],
       [0.70197809, 0.61472958, 0.37379017, 0.23347293, 0.96486165],
       [0.8498736 , 0.19113114, 0.47651905, 0.44417057, 0.43818101],
       [0.27009967, 0.99073835, 0.19730006, 0.26458451, 0.99506878],
       [0.6780229 , 0.41632616, 0.30870834, 0.48656199, 0.15924925]])

In [52]:
M[1,1]

0.6147295804984785

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [53]:
M

array([[0.05443279, 0.5865209 , 0.41960066, 0.55987282, 0.82611659],
       [0.70197809, 0.61472958, 0.37379017, 0.23347293, 0.96486165],
       [0.8498736 , 0.19113114, 0.47651905, 0.44417057, 0.43818101],
       [0.27009967, 0.99073835, 0.19730006, 0.26458451, 0.99506878],
       [0.6780229 , 0.41632616, 0.30870834, 0.48656199, 0.15924925]])

In [54]:
M[1]

array([0.70197809, 0.61472958, 0.37379017, 0.23347293, 0.96486165])

The same thing can be achieved with using `:` instead of an index: 

In [55]:
M[1,:] # row 1

array([0.70197809, 0.61472958, 0.37379017, 0.23347293, 0.96486165])

In [56]:
M[:,1] # column 1

array([0.5865209 , 0.61472958, 0.19113114, 0.99073835, 0.41632616])

We can assign new values to elements in an array using indexing:

In [57]:
M[0,0] = 1

In [58]:
M

array([[1.        , 0.5865209 , 0.41960066, 0.55987282, 0.82611659],
       [0.70197809, 0.61472958, 0.37379017, 0.23347293, 0.96486165],
       [0.8498736 , 0.19113114, 0.47651905, 0.44417057, 0.43818101],
       [0.27009967, 0.99073835, 0.19730006, 0.26458451, 0.99506878],
       [0.6780229 , 0.41632616, 0.30870834, 0.48656199, 0.15924925]])

In [59]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [60]:
M

array([[ 1.        ,  0.5865209 , -1.        ,  0.55987282,  0.82611659],
       [ 0.        ,  0.        , -1.        ,  0.        ,  0.        ],
       [ 0.8498736 ,  0.19113114, -1.        ,  0.44417057,  0.43818101],
       [ 0.27009967,  0.99073835, -1.        ,  0.26458451,  0.99506878],
       [ 0.6780229 ,  0.41632616, -1.        ,  0.48656199,  0.15924925]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [61]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [62]:
A[1::2]

array([2, 4])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [63]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [64]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [65]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [66]:
A[:3] # first three elements

array([ 1, -2, -3])

In [67]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [68]:
A = np.array([1,2,3,4,5])
print(A)

[1 2 3 4 5]


In [69]:
A[-1] # the last element in the array

5

In [70]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [71]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [72]:
HH = np.array([[1.0/(n+m+1) for n in range(5)] for m in range(5)])

In [73]:
HH

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [74]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [75]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [76]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [77]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [78]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices,col_indices]

array([11, 22, 34])

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [79]:
B = np.array([n for n in range(5)])
B

array([0, 1, 2, 3, 4])

In [80]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [81]:
# same thing
row_mask = np.array([5,0,1,0,0], dtype=bool)
print(row_mask)
B[row_mask]

[ True False  True False False]


array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [82]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [83]:
mask1 = (5 < x)

mask2 = (x < 7.5)

mask1

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [84]:
mask2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [85]:
mask = (5 < x) * (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [86]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [87]:
index=np.arange(0,x.size)
index
index[mask]

array([11, 12, 13, 14])

**Exercise.** Sometimes in matrices we have missing values that can be repsented either by NaN (`np.nan`) or Infinity (`np.inf`). Starting from the following matrix
$M=\left[\begin{matrix}
  1 & 2 & 3 & 4 \\
  3 & 4 & 5 & 6 \\
  5 & 6 & 7 & 8
\end{matrix}\right]$, substitute the element in position $(1,1)$ with `np.nan` and the element in position $(1,3)$ with `np.inf`. 
Use a mask to substitue all the occurences of NaN and Inf with -1.

## Functions for extracting data from arrays and creating arrays

### where

The index mask can be converted to position index using the `where` function

In [88]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [89]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

array([5.5, 6. , 6.5, 7. ])

### diag

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [90]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [91]:
np.diag(A)

array([ 0, 11, 22, 33, 44])

In [92]:
np.diag(A, -1)

array([10, 21, 32, 43])

### take

The `take` function is similar to fancy indexing described above:

In [93]:
v2 = np.arange(-3,3)
v2

array([-3, -2, -1,  0,  1,  2])

In [94]:
row_indices = [1, 3, 5]
v2[row_indices] # fancy indexing

array([-2,  0,  2])

In [95]:
v2.take(row_indices)

array([-2,  0,  2])

But `take` also works on lists and other objects:

In [96]:
np.take([-3, -2, -1,  0,  1,  2], row_indices)

array([-2,  0,  2])

### choose

Constructs an array by picking elements from several arrays:

In [97]:
help(np.choose)

Help on function choose in module numpy:

choose(a, choices, out=None, mode='raise')
    Construct an array from an index array and a list of arrays to choose from.
    
    First of all, if confused or uncertain, definitely look at the Examples -
    in its full generality, this function is less simple than it might
    seem from the following code description (below ndi =
    `numpy.lib.index_tricks`):
    
    ``np.choose(a,c) == np.array([c[a[I]][I] for I in ndi.ndindex(a.shape)])``.
    
    But this omits some subtleties.  Here is a fully general summary:
    
    Given an "index" array (`a`) of integers and a sequence of ``n`` arrays
    (`choices`), `a` and each choice array are first broadcast, as necessary,
    to arrays of a common shape; calling these *Ba* and *Bchoices[i], i =
    0,...,n-1* we have that, necessarily, ``Ba.shape == Bchoices[i].shape``
    for each ``i``.  Then, a new array with shape ``Ba.shape`` is created as
    follows:
    
    * if ``mode='raise'`` (t

In [98]:
which = [1, 0, 1, 2]
choices = [[1,2,3,4], [-5,-6,-7,-8], [9, 8, 65, 55]]

np.choose(which, choices)

array([-5,  2, -7, 55])

The first element of the result will be the first element of second "array" in choices; the second element
will be the second element of the first choice array, etc.

### Calculations with higher-dimensional data

When functions such as `min`, `max`, etc. are applied to a multidimensional arrays, it is sometimes useful to apply the calculation to the entire array, and sometimes only on a row or column basis. Using the `axis` argument we can specify how these functions should behave: 

In [99]:
m = random.rand(3,3)
m

array([[0.56420886, 0.52604104, 0.64816866],
       [0.78808464, 0.01871555, 0.53886337],
       [0.79706219, 0.74479459, 0.59484477]])

In [100]:
# global max
m.max()

0.7970621885973169

In [101]:
# max in each column
m.max(axis=0)

array([0.79706219, 0.74479459, 0.64816866])

In [102]:
# max in each row
m.max(axis=1)

array([0.64816866, 0.78808464, 0.79706219])

Many other functions and methods in the `array` and `matrix` classes accept the same (optional) `axis` keyword argument.

## Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [103]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [104]:
n, m = A.shape
print(n,m)

5 5


In [105]:
B = A.reshape((1,n*m))
B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [106]:
B[0,0:5] = 5 # modify the array

B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [107]:
A # and the original variable is also changed. B is only a different view of the same data

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

We can also use the function `flatten` to make a higher-dimensional array into a vector. But this function create a copy of the data.

In [108]:
B = A.flatten()

B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [109]:
B[0:5] = 10

B

array([10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [110]:
A # now A has not changed, because B's data is a copy of A's, not refering to the same data

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

## Adding a new dimension: newaxis

With `newaxis`, we can insert new dimensions in an array, for example converting a vector to a column or row matrix:

In [111]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [112]:
np.shape(v)

(3,)

In [113]:
# make a column matrix of the vector v
vc=v[:, np.newaxis]
vc

array([[1],
       [2],
       [3]])

In [114]:
# column matrix
v[:,np.newaxis].shape

(3, 1)

In [115]:
# make a row matrix of the vector v
vr=v[np.newaxis,:]
vr

array([[1, 2, 3]])

In [116]:
# row matrix
v[np.newaxis,:].shape

(1, 3)

In [117]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])
x1+x2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
x1_new = x1[:,np.newaxis]

In [ ]:
x1_new+x2

## Stacking and repeating arrays

Using function `repeat`, `tile`, `vstack`, `hstack`, and `concatenate` we can create larger vectors and matrices from smaller ones:

### tile and repeat

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

In [ ]:
# repeat each element 3 times
np.repeat(a, 3)

In [ ]:
# tile the matrix 3 times 
np.tile(a, 3)

### concatenate

In [ ]:
b = np.array([[5, 6]])
print(a,b)

In [ ]:
np.concatenate((a, b), axis=0)

In [ ]:
np.concatenate((a, b), axis=1)

### hstack and vstack

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b.T))

## Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference). 

In [ ]:
A = np.array([[1, 2], [3, 4]])

A

In [ ]:
# now B is referring to the same array data as A 
B = A 

In [ ]:
# changing B affects A
B[0,0] = 10

B

In [ ]:
A

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "deep copy" using the function `copy`:

In [ ]:
B = np.copy(A)

In [ ]:
# now, if we modify B, A is not affected
B[0,0] = -5

B

In [ ]:
A

## Iterating over array elements

Generally, we want to avoid iterating over the elements of arrays whenever we can (at all costs). The reason is that in a interpreted language like Python (or MATLAB), iterations are really slow compared to vectorized operations. 

However, sometimes iterations are unavoidable. For such cases, the Python `for` loop is the most convenient way to iterate over an array:

In [ ]:
v = np.array([1,2,3,4])

for element in v:
    print(element)

In [ ]:
M = np.array([[1,2], [3,4]])

for row in M:
    print("row", row)
    
    for element in row:
        print(element)

In [ ]:
M

When we need to iterate over each element of an array and modify its elements, it is convenient to use the `enumerate` function to obtain both the element and its index in the `for` loop: 

In [ ]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)
    
    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)
       
        # update the matrix M: square each element
        M[row_idx, col_idx] = element ** 2

In [ ]:
# each element in M is now squared
M

## Using arrays in conditions

When using arrays in conditions,for example `if` statements and other boolean expressions, one needs to use `any` or `all`, which requires that any or all elements in the array evalutes to `True`:

In [ ]:
M

In [ ]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

In [ ]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

## Type casting

Since Numpy arrays are *statically typed*, the type of an array does not change once created. But we can explicitly cast an array of some type to another using the `astype` functions (see also the similar `asarray` function). This always create a new array of new type:

In [ ]:
M.dtype

In [ ]:
M = M.astype(complex)

M

In [ ]:
M.dtype

In [ ]:
M3 = M.astype(float)

M3